"""Add cached_report column to review

Revision ID: ad007ada922d
Revises: d5324c7c8c24
Create Date: 2026-07-06 23:12:00.462262

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ad007ada922d'
down_revision: Union[str, Sequence[str], None] = 'd5324c7c8c24'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reviews', sa.Column('cached_report', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reviews', 'cached_report')
    # ### end Alembic commands ###
