"""Add recommendations column to review table

Revision ID: d5324c7c8c24
Revises: ec661d8ed003
Create Date: 2026-07-06 23:06:58.106860

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd5324c7c8c24'
down_revision: Union[str, Sequence[str], None] = 'ec661d8ed003'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reviews', sa.Column('recommendations', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reviews', 'recommendations')
    # ### end Alembic commands ###
