from pathlib import Path
from app.services.aggregation.dto import CanonicalReviewReport

class MarkdownExporter:
    @staticmethod
    def export(report: CanonicalReviewReport, output_path: Path) -> str:
        md = []
        md.append(f"# CodeSage Review Report")
        md.append(f"**Project ID:** {report.project_id}")
        md.append(f"**Review ID:** {report.review_id}")
        md.append(f"**Generated At:** {report.created_at}")
        md.append(f"**Status:** {report.status.value}")
        md.append("")

        md.append(f"## Executive Summary")
        md.append(f"**Overall Score:** {report.score} / 100")
        md.append(f"**Grade:** {report.grade}")
        md.append("")
        md.append(report.summary or "No summary provided.")
        md.append("")

        if report.ai_summary:
            md.append(f"### AI Mentor Insights")
            md.append(report.ai_summary)
            md.append("")

        if report.recommendations:
            md.append(f"## Recommendations")
            for rec in report.recommendations:
                md.append(f"- **{rec.get('title')}**: {rec.get('description')} (*Impact: {rec.get('impact')}*)")
            md.append("")

        md.append(f"## Statistics")
        md.append(f"- **Total Findings:** {report.statistics.total_findings}")
        md.append(f"- **Critical:** {report.statistics.critical_count}")
        md.append(f"- **High:** {report.statistics.high_count}")
        md.append(f"- **Medium:** {report.statistics.medium_count}")
        md.append(f"- **Low:** {report.statistics.low_count}")
        md.append(f"- **Files Analyzed:** {report.statistics.files_analyzed}")
        md.append("")

        md.append(f"## Findings")
        if not report.findings:
            md.append("No findings to report.")
        else:
            for f in report.findings:
                md.append(f"### [{f.severity.value}] {f.title}")
                md.append(f"- **Source:** {f.source.value}")
                md.append(f"- **Location:** `{f.file_path}:{f.line}`")
                if f.description:
                    md.append(f"- **Description:** {f.description}")
                if f.recommendation:
                    md.append(f"- **Suggestion:** {f.recommendation}")
                md.append("")

        md.append(f"## Metrics")
        for m in report.metrics:
            md.append(f"- **{m.metric_name}:** {m.metric_value} {m.unit or ''}")
        md.append("")

        md.append("---")
        md.append("*Generated by CodeSage AI Code Reviewer*")

        with open(output_path, "w", encoding="utf-8") as f:
            f.write("\n".join(md))

        return str(output_path)
