from pathlib import Path
from reportlab.lib.pagesizes import letter
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib import colors
from app.services.aggregation.dto import CanonicalReviewReport

class PDFExporter:
    @staticmethod
    def export(report: CanonicalReviewReport, output_path: Path) -> str:
        doc = SimpleDocTemplate(str(output_path), pagesize=letter)
        styles = getSampleStyleSheet()
        story = []

        # Title
        title_style = ParagraphStyle(
            'TitleStyle',
            parent=styles['Heading1'],
            fontSize=24,
            spaceAfter=20,
            textColor=colors.HexColor("#6366f1")
        )
        story.append(Paragraph(f"CodeSage Review Report", title_style))
        story.append(Paragraph(f"Review ID: {report.review_id}", styles['Normal']))
        story.append(Paragraph(f"Project ID: {report.project_id}", styles['Normal']))
        story.append(Paragraph(f"Generated At: {report.created_at.strftime('%Y-%m-%d %H:%M:%S')}", styles['Normal']))
        story.append(Spacer(1, 12))

        # Executive Summary
        story.append(Paragraph("Executive Summary", styles['Heading2']))
        summary_data = [
            ["Overall Score", f"{report.score} / 100"],
            ["Letter Grade", report.grade],
            ["Status", report.status.value]
        ]
        t = Table(summary_data, colWidths=[150, 200])
        t.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (0, -1), colors.whitesmoke),
            ('TEXTCOLOR', (0, 0), (0, -1), colors.darkgrey),
            ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
            ('FONTNAME', (0, 0), (-1, -1), 'Helvetica-Bold'),
            ('GRID', (0, 0), (-1, -1), 0.5, colors.grey),
            ('PADDING', (0, 0), (-1, -1), 8),
        ]))
        story.append(t)
        story.append(Spacer(1, 12))
        story.append(Paragraph(report.summary or "No summary provided.", styles['Normal']))
        story.append(Spacer(1, 12))

        # Stats
        story.append(Paragraph("Statistics", styles['Heading2']))
        stats = report.statistics
        stats_data = [
            ["Total Findings", str(stats.total_findings)],
            ["Critical", str(stats.critical_count)],
            ["High", str(stats.high_count)],
            ["Medium", str(stats.medium_count)],
            ["Low", str(stats.low_count)],
            ["Duration (ms)", str(stats.duration_ms)]
        ]
        st = Table(stats_data, colWidths=[150, 100])
        st.setStyle(TableStyle([
            ('GRID', (0, 0), (-1, -1), 0.5, colors.grey),
            ('BACKGROUND', (0, 0), (0, -1), colors.whitesmoke),
            ('PADDING', (0, 0), (-1, -1), 6),
        ]))
        story.append(st)
        story.append(Spacer(1, 20))

        # AI Recommendations
        if report.recommendations:
            story.append(Paragraph("AI Mentor Recommendations", styles['Heading2']))
            for rec in report.recommendations:
                story.append(Paragraph(f"<b>{rec.get('title')}</b>", styles['Normal']))
                story.append(Paragraph(rec.get('description'), styles['Normal']))
                story.append(Paragraph(f"<i>Impact: {rec.get('impact')}</i>", styles['Small']))
                story.append(Spacer(1, 8))
            story.append(Spacer(1, 12))

        # Findings
        story.append(Paragraph("Detailed Findings", styles['Heading2']))
        if not report.findings:
            story.append(Paragraph("No findings to report.", styles['Normal']))
        else:
            for f in report.findings[:50]: # Limit for PDF size in skeleton
                severity_color = colors.grey
                if f.severity == "CRITICAL": severity_color = colors.red
                elif f.severity == "HIGH": severity_color = colors.orange
                elif f.severity == "MEDIUM": severity_color = colors.gold

                story.append(Paragraph(f"<font color='{severity_color.hexval()}'>[{f.severity.value}]</font> {f.title}", styles['Heading3']))
                story.append(Paragraph(f"Source: {f.source.value} | File: {f.file_path}:{f.line}", styles['Small']))
                if f.description:
                    story.append(Paragraph(f.description, styles['Normal']))
                if f.recommendation:
                    story.append(Paragraph(f"<b>Recommendation:</b> {f.recommendation}", styles['Normal']))
                story.append(Spacer(1, 10))

        # Footer
        story.append(Spacer(1, 40))
        story.append(Paragraph("Generated by CodeSage AI Code Reviewer", styles['Small']))

        doc.build(story)
        return str(output_path)
